// Data shared across pages (films, faqs, etc.)

window.iLPFData = {
  films: [
    { t: "Sheriff: Narko-Integriti 2", cls: "18", jenis: "Pawagam", pengedar: "Astro Shaw Sdn Bhd", date: "28 Apr 2026", cert: "A2026/04/0892" },
    { t: "Dune: Part Three", cls: "p12", jenis: "Pawagam", pengedar: "Warner Bros Malaysia", date: "22 Apr 2026", cert: "A2026/04/0871" },
    { t: "Mat Kilau: Pendekar Pahang", cls: "13", jenis: "Pawagam", pengedar: "Studio Kembara", date: "18 Apr 2026", cert: "A2026/04/0834" },
    { t: "Imaginur 2", cls: "p12", jenis: "Pawagam", pengedar: "Layar Sunan", date: "11 Apr 2026", cert: "A2026/04/0801" },
    { t: "Inside Out 3", cls: "u", jenis: "Pawagam", pengedar: "Walt Disney Malaysia", date: "4 Apr 2026", cert: "A2026/04/0762" },
    { t: "Polis Evo 4", cls: "16", jenis: "Pawagam", pengedar: "Astro Shaw Sdn Bhd", date: "28 Mac 2026", cert: "A2026/03/0728" },
    { t: "The Batman Part II", cls: "18", jenis: "Pawagam", pengedar: "Warner Bros Malaysia", date: "21 Mac 2026", cert: "A2026/03/0699" },
    { t: "Upin & Ipin: Lagenda Pulau", cls: "u", jenis: "Pawagam", pengedar: "Les' Copaque Production", date: "14 Mac 2026", cert: "A2026/03/0661" },
    { t: "Mission: Impossible 8", cls: "p12", jenis: "Pawagam", pengedar: "UIP Malaysia", date: "28 Feb 2026", cert: "A2026/02/0594" },
    { t: "Drama Pilihan Malaya (Ep. 1–12)", cls: "13", jenis: "Tayangan TV", pengedar: "RTM", date: "15 Feb 2026", cert: "TV2026/02/0421" },
    { t: "Pendekar Bujang Lapok Remake", cls: "p12", jenis: "Pita & DVD", pengedar: "Filem Negara Malaysia", date: "8 Feb 2026", cert: "B2026/02/0387" },
    { t: "Iklan Petronas Tahun Baharu Cina 2026", cls: "u", jenis: "Iklan", pengedar: "Naga DDB Tribal", date: "2 Feb 2026", cert: "I2026/02/0353" },
    { t: "Spider-Man: Beyond the Spider-Verse", cls: "p12", jenis: "Pawagam", pengedar: "Sony Pictures Malaysia", date: "24 Jan 2026", cert: "A2026/01/0298" },
    { t: "Bercakap Dengan Jin: Episod Akhir", cls: "18", jenis: "Pawagam", pengedar: "KRU Studios", date: "17 Jan 2026", cert: "A2026/01/0264" },
    { t: "Bahan Publisiti — Trailer 'Sheriff 2'", cls: "18", jenis: "Bahan Publisiti", pengedar: "Astro Shaw Sdn Bhd", date: "10 Jan 2026", cert: "BP2026/01/0182" },
    { t: "Avatar: Fire and Ash", cls: "p12", jenis: "Pawagam", pengedar: "20th Century Studios MY", date: "18 Dis 2025", cert: "A2025/12/3847" },
    { t: "Mufasa: The Lion King", cls: "u", jenis: "Pawagam", pengedar: "Walt Disney Malaysia", date: "11 Dis 2025", cert: "A2025/12/3812" },
    { t: "Wonka 2", cls: "u", jenis: "Pawagam", pengedar: "Warner Bros Malaysia", date: "4 Dis 2025", cert: "A2025/12/3776" },
    { t: "Ejen Ali The Movie 3", cls: "u", jenis: "Pawagam", pengedar: "WAU Animation", date: "14 Nov 2025", cert: "A2025/11/3681" },
    { t: "Pulang: Sang Pelarian", cls: "16", jenis: "Pita & DVD", pengedar: "Layar Sunan", date: "7 Nov 2025", cert: "B2025/11/3643" },
  ],
  classifications: [
    { id: "u",   t: "Umum",                  age: "Semua peringkat umur",
      desc: "Sesuai untuk seluruh keluarga.",
      points: ["Kandungan yang sesuai untuk seluruh keluarga.", "Tiada keganasan yang mengganggu, bahasa kasar, atau tema dewasa.", "Mesej positif dan nilai sejagat."],
      examples: ["Upin & Ipin: Lagenda Pulau", "Mufasa: The Lion King", "Inside Out 3"] },
    { id: "p12", t: "Bimbingan Ibu Bapa 12+", age: "12 tahun dan ke atas (bimbingan ibu bapa untuk bawah 12)",
      desc: "Bimbingan ibu bapa untuk penonton bawah 12 tahun.",
      points: ["Tema yang mungkin memerlukan penjelasan ibu bapa.", "Aksi ringan tanpa keganasan yang panjang lebar.", "Bahasa yang sopan dengan beberapa pengecualian kecil."],
      examples: ["Dune: Part Three", "Mission: Impossible 8", "Imaginur 2"] },
    { id: "13",  t: "Bimbingan 13+",         age: "13 tahun dan ke atas",
      desc: "Tidak sesuai untuk kanak-kanak.",
      points: ["Aksi dan keganasan yang lebih intens, namun tidak grafik.", "Tema sosial yang kompleks (politik, persahabatan, identiti).", "Bahasa kasar yang terhad."],
      examples: ["Mat Kilau: Pendekar Pahang", "Drama Pilihan Malaya", "Pendekar Bujang Lapok"] },
    { id: "16",  t: "Belia 16+",             age: "16 tahun dan ke atas",
      desc: "Tidak sesuai untuk bawah 16.",
      points: ["Keganasan yang lebih realistik.", "Bahasa kasar yang lebih kerap.", "Tema dewasa: jenayah serius, dadah, perhubungan kompleks."],
      examples: ["Polis Evo 4", "Pulang: Sang Pelarian"] },
    { id: "18",  t: "Dewasa 18+",            age: "Hanya 18 tahun dan ke atas",
      desc: "Pengesahan umur diperlukan di pintu masuk pawagam.",
      points: ["Keganasan grafik, tema gelap, atau seram yang intens.", "Bahasa kasar tanpa had.", "Tema dewasa yang eksplisit dalam konteks naratif."],
      examples: ["Sheriff: Narko-Integriti 2", "The Batman Part II", "Bercakap Dengan Jin"] },
  ],
  piagam: [
    { dur: "5", svc: "Sijil Tayangan Video (STV)", was: "10 hari", state: "down", pct: "−50%" },
    { dur: "2", svc: "Bahan Publisiti",            was: "3 hari",  state: "down", pct: "−33%" },
    { dur: "5", svc: "Tayangan Pawagam (Sijil A)", was: "5 hari",  state: "same", pct: "Sama" },
    { dur: "5", svc: "Perakuan A — Pita & DVD",    was: "10 hari", state: "down", pct: "−50%" },
    { dur: "5", svc: "Iklan TV & Pawagam",         was: "5 hari",  state: "same", pct: "Sama" },
  ],
  faqs: [
    { c: "umum", q: "Apakah iLPF v2?",
      a: "iLPF v2 adalah platform digital baharu Lembaga Penapisan Filem Malaysia. Ia menggantikan sistem lama dengan antara muka yang lebih bersih, aliran kerja yang lebih pantas, dan Piagam Pelanggan yang dipendekkan separuh untuk dua perkhidmatan utama." },
    { c: "umum", q: "Siapa yang perlu menggunakan iLPF?",
      a: "Pengedar filem, stesen TV, agensi pengiklanan, dan rumah produksi yang ingin menapis filem, rancangan, atau bahan publisiti untuk tayangan di Malaysia. Pegawai PPF dan Ahli Lembaga (ALPF) menggunakan portal yang berasingan." },
    { c: "permohonan", q: "Berapa lama proses tapisan filem mengambil masa?",
      a: "Mengikut Piagam Pelanggan 2026: Sijil Tayangan Video (STV) 5 hari bekerja, Bahan Publisiti 2 hari, Tayangan Pawagam 5 hari, Perakuan A Pita/DVD 5 hari, Iklan 5 hari. Tempoh dikira dari tarikh permohonan lengkap diterima." },
    { c: "permohonan", q: "Apakah dokumen yang diperlukan untuk menghantar filem?",
      a: "Salinan master filem (resolusi penuh), sinopsis dalam Bahasa Malaysia, senarai pelakon dan kru, sijil hak cipta atau lesen pengedaran, dan bayaran yuran tapisan. Untuk filem import, permit Bahagian Kawalan Filem diperlukan." },
    { c: "yuran", q: "Bagaimana yuran tapisan dikira?",
      a: "Yuran dikira mengikut Peraturan-Peraturan Penapisan (Fi) Filem 1984. Faktor utama: tempoh tayangan filem (mengikut minit), jenis permohonan, dan format penyerahan. Gunakan Kalkulator Yuran di portal untuk anggaran tepat." },
    { c: "yuran", q: "Bagaimana saya boleh membayar yuran?",
      a: "Pembayaran dalam talian melalui FPX (semua bank tempatan), kad kredit/debit, atau ePay. Resit dijana secara automatik selepas pembayaran berjaya. Bayaran kaunter masih diterima di pejabat PPF Putrajaya." },
    { c: "klasifikasi", q: "Apakah maksud klasifikasi U, P12, 13, 16, dan 18?",
      a: "U (Umum) sesuai untuk semua. P12 memerlukan bimbingan ibu bapa untuk bawah 12 tahun. 13 untuk 13 tahun ke atas. 16 untuk 16 tahun ke atas. 18 untuk dewasa sahaja, dengan pengesahan umur di pawagam." },
    { c: "klasifikasi", q: "Bagaimana klasifikasi diputuskan?",
      a: "Setiap filem ditapis oleh panel tiga Ahli Lembaga Penapisan Filem (ALPF) mengikut Garis Panduan Penapisan Filem 2026. Klasifikasi diberikan berdasarkan keseluruhan kandungan — bukan satu adegan terpencil." },
    { c: "rayuan", q: "Bolehkah saya membuat rayuan jika filem saya ditolak?",
      a: "Ya. Di bawah seksyen 21 Akta Penapisan Filem 2002, anda boleh membuat rayuan kepada Jawatankuasa Rayuan Filem dalam tempoh 30 hari dari tarikh keputusan. Borang rayuan dan panduan tersedia di portal." },
    { c: "akaun", q: "Bagaimana saya mendaftar akaun pengedar?",
      a: "Klik 'Log Masuk → Pengedar Filem → Daftar Akaun'. Anda perlu menyediakan dokumen syarikat (SSM), maklumat pegawai dihubungi, dan pengesahan emel. Pengesahan akaun mengambil 1–2 hari bekerja." },
    { c: "akaun", q: "Saya lupa kata laluan. Apa patut saya buat?",
      a: "Di halaman log masuk, klik 'Lupa kata laluan'. Pautan tetap semula akan dihantar ke emel berdaftar dalam masa 5 minit. Jika tidak diterima, semak folder spam atau hubungi sokongan teknikal." },
  ],
  stats2026: {
    byType: [
      { l: "Tayangan TV",      v: 612, c: "#003D3A" },
      { l: "Tayangan Panggung",v: 487, c: "#00B8A9" },
      { l: "Bahan Publisiti",  v: 423, c: "#F4B400" },
      { l: "Iklan",            v: 198, c: "#FF6B35" },
      { l: "Pita & DVD",       v: 127, c: "#9CA3AF" },
    ],
    byCls: [
      { l: "U",   v: 612, c: "#10B981" },
      { l: "P12", v: 287, c: "#3B82F6" },
      { l: "13",  v: 451, c: "#F4B400" },
      { l: "16",  v: 312, c: "#EF4444" },
      { l: "18",  v: 185, c: "#0A0E13" },
    ],
  },
};
